model_list:
  - model_name: gemini
    litellm_params:
      model: openai/google.gemini-2.5-flash
      api_base: https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/openai/v1
      api_key: os.environ/OCI_GENAI_API_KEY
      extra_headers:
        OpenAI-Project: os.environ/OCI_GENAI_PROJECT_ID

  - model_name: grok
    litellm_params:
      model: openai/xai.grok-4.3
      api_base: https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/openai/v1
      api_key: os.environ/OCI_GENAI_API_KEY
      extra_headers:
        OpenAI-Project: os.environ/OCI_GENAI_PROJECT_ID
